Basic implementation
exasol/artifact-reference-checker-maven-plugin pull request #1
Opened 2020-08-27 11:02 UTC by jakobbraun

2020-08-31 12:08 UTC, morazow requested changes

2020-08-31 12:08 UTC, morazow commented on .travis.yml
> +      #secure: nIy8nwbtC6mGYJXDO3itMPwJwuwY9j2whvoJY50g98Nye8PEXVF8WlEFJUYogwtzq9arDc5BWHnyw04dgkH8nDlDUjXiE2G8gwl0W918cRCiUlwMd6pvE32hM82mhqJ9hGajMVisVNtmmvQo4zUwNcc9DfWHvOvbacYPhzO+x5w7DuTPB7rbQhir
Remove this if it is already provided in Travis UI.

2020-08-31 12:08 UTC, morazow commented on README.md
> +This [Maven-Plugin](https://maven.apache.org/plugins/index.html) helps you not to forget to change reference to your artifacts.
```suggestion
This [Maven-Plugin](https://maven.apache.org/plugins/index.html) helps you not to forget to change references to your artifacts.
```

2020-08-31 12:08 UTC, morazow commented on pom.xml
> +    <version>0.0.1</version>
Change this to the release version, `0.1.0`.

2020-08-31 12:08 UTC, morazow commented on pom.xml
> +        <maven.compiler.source>1.8</maven.compiler.source>
You can start immediately using Java 11, if there are no blockers to do so.

2020-08-31 12:08 UTC, morazow commented on pom.xml
> +            <scope>provided</scope>
Does this mean the users should add this annotations plugin to their pom files?
If so, please add this an requirement/prerequisite to the readme. Or to the installation section in readme.

2020-08-31 12:08 UTC, morazow commented on pom.xml
> +            <scope>provided</scope>
Okay, similar prerequisite seems to be assembly plugin. Add it also as a requirement for this to work.

2020-08-31 12:08 UTC, morazow commented on src/main/java/com/exasol/artifactreferencechecker/ArtifactReferenceCheckerMojo.java
> +                .orElseThrow(() -> new IllegalStateException("Could not find assembly plugin."));
You can also think about supporting projects without assembly plugin.

2020-08-31 12:08 UTC, morazow commented on src/main/java/com/exasol/artifactreferencechecker/ArtifactReferenceCheckerMojo.java
> +                        "Could not open project file " + file.toString() + ". Cause: " + exception.getMessage(),
I think, you can remove the cause. It should propagate with exception.

Usually, cause is required in our udfs.

2020-08-31 12:08 UTC, morazow commented on pom.xml
> +        <plugins>
Once it is published, it would nice to check itself also :)

2020-09-04 08:26 UTC, jakobbraun commented on pom.xml
> +        <plugins>
well yes. I thought about that too. The problem is, that this one is different since it is not used a jar but as a maven plugin definition. So it is much harder to scan.

2020-09-04 08:26 UTC, jakobbraun commented on src/main/java/com/exasol/artifactreferencechecker/ArtifactReferenceCheckerMojo.java
> +                .orElseThrow(() -> new IllegalStateException("Could not find assembly plugin."));
Do you have a use case for that?

2020-09-04 08:26 UTC, jakobbraun commented on pom.xml
> +        <maven.compiler.source>1.8</maven.compiler.source>
Since I'm using java 11 some lines below, I think I can remove these lines?

2020-09-04 08:26 UTC, jakobbraun commented on pom.xml
> +            <scope>provided</scope>
I think the assembly plugin is shipped with maven anyway?

2020-09-04 08:27 UTC, jakobbraun commented on .travis.yml
> +      #secure: nIy8nwbtC6mGYJXDO3itMPwJwuwY9j2whvoJY50g98Nye8PEXVF8WlEFJUYogwtzq9arDc5BWHnyw04dgkH8nDlDUjXiE2G8gwl0W918cRCiUlwMd6pvE32hM82mhqJ9hGajMVisVNtmmvQo4zUwNcc9DfWHvOvbacYPhzO+x5w7DuTPB7rbQhir
I replaced it by the correct one.

2020-09-04 08:37 UTC, morazow requested changes

2020-09-04 08:37 UTC, morazow commented on pom.xml
> +            <scope>provided</scope>
I am not aware of that :) If so then it is good.

2020-09-04 08:37 UTC, morazow commented on pom.xml
> +        <plugins>
:+1:

2020-09-04 08:37 UTC, morazow commented on src/main/java/com/exasol/artifactreferencechecker/ArtifactReferenceCheckerMojo.java
> +                .orElseThrow(() -> new IllegalStateException("Could not find assembly plugin."));
This was also about the previous comment. I thought that the assembly plugin is prerequisite, but if it is available then all good.

I was thinking about the common libraries that a released to the sonatype/nexus. Maybe they do not need assembled uber jar, thus no need for the `maven-assembly-plugin`.

2020-09-04 08:39 UTC, morazow approved these changes

2020-09-04 08:47 UTC, merged